// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc_service.proto
// Protobuf C++ Version: 5.28.0-dev

#include "rpc_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace com {
namespace rpc {

inline constexpr ListRpcResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : service_name_{},
        method_name_{},
        error_{static_cast< ::com::rpc::ErrorCode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListRpcResponse::ListRpcResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListRpcResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListRpcResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListRpcResponseDefaultTypeInternal() {}
  union {
    ListRpcResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListRpcResponseDefaultTypeInternal _ListRpcResponse_default_instance_;

inline constexpr ListRpcRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : service_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        list_method_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListRpcRequest::ListRpcRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListRpcRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListRpcRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListRpcRequestDefaultTypeInternal() {}
  union {
    ListRpcRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListRpcRequestDefaultTypeInternal _ListRpcRequest_default_instance_;

inline constexpr GetServiceResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : proto_file_{},
        proto_file_name_{},
        error_{static_cast< ::com::rpc::ErrorCode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetServiceResponse::GetServiceResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetServiceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetServiceResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetServiceResponseDefaultTypeInternal() {}
  union {
    GetServiceResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetServiceResponseDefaultTypeInternal _GetServiceResponse_default_instance_;

inline constexpr GetServiceRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : service_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetServiceRequest::GetServiceRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetServiceRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetServiceRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetServiceRequestDefaultTypeInternal() {}
  union {
    GetServiceRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetServiceRequestDefaultTypeInternal _GetServiceRequest_default_instance_;
}  // namespace rpc
}  // namespace com
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_rpc_5fservice_2eproto = nullptr;
static const ::_pb::ServiceDescriptor*
    file_level_service_descriptors_rpc_5fservice_2eproto[1];
const ::uint32_t
    TableStruct_rpc_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::com::rpc::ListRpcRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::com::rpc::ListRpcRequest, _impl_.service_name_),
        PROTOBUF_FIELD_OFFSET(::com::rpc::ListRpcRequest, _impl_.list_method_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::com::rpc::ListRpcResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::com::rpc::ListRpcResponse, _impl_.error_),
        PROTOBUF_FIELD_OFFSET(::com::rpc::ListRpcResponse, _impl_.service_name_),
        PROTOBUF_FIELD_OFFSET(::com::rpc::ListRpcResponse, _impl_.method_name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::com::rpc::GetServiceRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::com::rpc::GetServiceRequest, _impl_.service_name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::com::rpc::GetServiceResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::com::rpc::GetServiceResponse, _impl_.error_),
        PROTOBUF_FIELD_OFFSET(::com::rpc::GetServiceResponse, _impl_.proto_file_),
        PROTOBUF_FIELD_OFFSET(::com::rpc::GetServiceResponse, _impl_.proto_file_name_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::com::rpc::ListRpcRequest)},
        {10, -1, -1, sizeof(::com::rpc::ListRpcResponse)},
        {21, -1, -1, sizeof(::com::rpc::GetServiceRequest)},
        {30, -1, -1, sizeof(::com::rpc::GetServiceResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::com::rpc::_ListRpcRequest_default_instance_._instance,
    &::com::rpc::_ListRpcResponse_default_instance_._instance,
    &::com::rpc::_GetServiceRequest_default_instance_._instance,
    &::com::rpc::_GetServiceResponse_default_instance_._instance,
};
const char descriptor_table_protodef_rpc_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021rpc_service.proto\022\007com.rpc\032\trpc.proto\""
    ";\n\016ListRpcRequest\022\024\n\014service_name\030\001 \001(\t\022"
    "\023\n\013list_method\030\002 \001(\010\"_\n\017ListRpcResponse\022"
    "!\n\005error\030\001 \001(\0162\022.com.rpc.ErrorCode\022\024\n\014se"
    "rvice_name\030\002 \003(\t\022\023\n\013method_name\030\003 \003(\t\")\n"
    "\021GetServiceRequest\022\024\n\014service_name\030\001 \001(\t"
    "\"d\n\022GetServiceResponse\022!\n\005error\030\001 \001(\0162\022."
    "com.rpc.ErrorCode\022\022\n\nproto_file\030\002 \003(\t\022\027\n"
    "\017proto_file_name\030\003 \003(\t2\221\001\n\nRpcService\022<\n"
    "\007listRpc\022\027.com.rpc.ListRpcRequest\032\030.com."
    "rpc.ListRpcResponse\022E\n\ngetService\022\032.com."
    "rpc.GetServiceRequest\032\033.com.rpc.GetServi"
    "ceResponseB\006\200\001\001\220\001\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_rpc_5fservice_2eproto_deps[1] =
    {
        &::descriptor_table_rpc_2eproto,
};
static ::absl::once_flag descriptor_table_rpc_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rpc_5fservice_2eproto = {
    false,
    false,
    506,
    descriptor_table_protodef_rpc_5fservice_2eproto,
    "rpc_service.proto",
    &descriptor_table_rpc_5fservice_2eproto_once,
    descriptor_table_rpc_5fservice_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_rpc_5fservice_2eproto::offsets,
    file_level_enum_descriptors_rpc_5fservice_2eproto,
    file_level_service_descriptors_rpc_5fservice_2eproto,
};
namespace com {
namespace rpc {
// ===================================================================

class ListRpcRequest::_Internal {
 public:
};

ListRpcRequest::ListRpcRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.rpc.ListRpcRequest)
}
inline PROTOBUF_NDEBUG_INLINE ListRpcRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::com::rpc::ListRpcRequest& from_msg)
      : service_name_(arena, from.service_name_),
        _cached_size_{0} {}

ListRpcRequest::ListRpcRequest(
    ::google::protobuf::Arena* arena,
    const ListRpcRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListRpcRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.list_method_ = from._impl_.list_method_;

  // @@protoc_insertion_point(copy_constructor:com.rpc.ListRpcRequest)
}
inline PROTOBUF_NDEBUG_INLINE ListRpcRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : service_name_(arena),
        _cached_size_{0} {}

inline void ListRpcRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.list_method_ = {};
}
ListRpcRequest::~ListRpcRequest() {
  // @@protoc_insertion_point(destructor:com.rpc.ListRpcRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ListRpcRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.service_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ListRpcRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ListRpcRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ListRpcRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ListRpcRequest>(),
            ::google::protobuf::Message::GetNewImpl<ListRpcRequest>(),
            ::google::protobuf::Message::GetClearImpl<ListRpcRequest>(),
                ::google::protobuf::Message::GetByteSizeLongImpl<ListRpcRequest>(),
                ::google::protobuf::Message::GetSerializeImpl<ListRpcRequest>(),
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ListRpcRequest, _impl_._cached_size_),
            false,
        },
        &ListRpcRequest::kDescriptorMethods,
        &descriptor_table_rpc_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ListRpcRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 43, 2> ListRpcRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::com::rpc::ListRpcRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool list_method = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ListRpcRequest, _impl_.list_method_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ListRpcRequest, _impl_.list_method_)}},
    // string service_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListRpcRequest, _impl_.service_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string service_name = 1;
    {PROTOBUF_FIELD_OFFSET(ListRpcRequest, _impl_.service_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool list_method = 2;
    {PROTOBUF_FIELD_OFFSET(ListRpcRequest, _impl_.list_method_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\26\14\0\0\0\0\0\0"
    "com.rpc.ListRpcRequest"
    "service_name"
  }},
};

PROTOBUF_NOINLINE void ListRpcRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:com.rpc.ListRpcRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.service_name_.ClearToEmpty();
  _impl_.list_method_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ListRpcRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.rpc.ListRpcRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string service_name = 1;
  if (!this->_internal_service_name().empty()) {
    const std::string& _s = this->_internal_service_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.rpc.ListRpcRequest.service_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bool list_method = 2;
  if (this->_internal_list_method() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_list_method(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.rpc.ListRpcRequest)
  return target;
}

::size_t ListRpcRequest::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:com.rpc.ListRpcRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(
      reinterpret_cast<const void*>(this));
   {
    // string service_name = 1;
    if (!this->_internal_service_name().empty()) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_service_name());
    }
    // bool list_method = 2;
    if (this->_internal_list_method() != 0) {
      total_size += 2;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void ListRpcRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListRpcRequest*>(&to_msg);
  auto& from = static_cast<const ListRpcRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.rpc.ListRpcRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_service_name().empty()) {
    _this->_internal_set_service_name(from._internal_service_name());
  }
  if (from._internal_list_method() != 0) {
    _this->_impl_.list_method_ = from._impl_.list_method_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListRpcRequest::CopyFrom(const ListRpcRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.rpc.ListRpcRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListRpcRequest::InternalSwap(ListRpcRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.service_name_, &other->_impl_.service_name_, arena);
        swap(_impl_.list_method_, other->_impl_.list_method_);
}

::google::protobuf::Metadata ListRpcRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListRpcResponse::_Internal {
 public:
};

ListRpcResponse::ListRpcResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.rpc.ListRpcResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListRpcResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::com::rpc::ListRpcResponse& from_msg)
      : service_name_{visibility, arena, from.service_name_},
        method_name_{visibility, arena, from.method_name_},
        _cached_size_{0} {}

ListRpcResponse::ListRpcResponse(
    ::google::protobuf::Arena* arena,
    const ListRpcResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListRpcResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.error_ = from._impl_.error_;

  // @@protoc_insertion_point(copy_constructor:com.rpc.ListRpcResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListRpcResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : service_name_{visibility, arena},
        method_name_{visibility, arena},
        _cached_size_{0} {}

inline void ListRpcResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_ = {};
}
ListRpcResponse::~ListRpcResponse() {
  // @@protoc_insertion_point(destructor:com.rpc.ListRpcResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ListRpcResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ListRpcResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ListRpcResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ListRpcResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ListRpcResponse>(),
            ::google::protobuf::Message::GetNewImpl<ListRpcResponse>(),
            ::google::protobuf::Message::GetClearImpl<ListRpcResponse>(),
                ::google::protobuf::Message::GetByteSizeLongImpl<ListRpcResponse>(),
                ::google::protobuf::Message::GetSerializeImpl<ListRpcResponse>(),
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ListRpcResponse, _impl_._cached_size_),
            false,
        },
        &ListRpcResponse::kDescriptorMethods,
        &descriptor_table_rpc_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ListRpcResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 55, 2> ListRpcResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::com::rpc::ListRpcResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .com.rpc.ErrorCode error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ListRpcResponse, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ListRpcResponse, _impl_.error_)}},
    // repeated string service_name = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ListRpcResponse, _impl_.service_name_)}},
    // repeated string method_name = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ListRpcResponse, _impl_.method_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .com.rpc.ErrorCode error = 1;
    {PROTOBUF_FIELD_OFFSET(ListRpcResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated string service_name = 2;
    {PROTOBUF_FIELD_OFFSET(ListRpcResponse, _impl_.service_name_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string method_name = 3;
    {PROTOBUF_FIELD_OFFSET(ListRpcResponse, _impl_.method_name_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\27\0\14\13\0\0\0\0"
    "com.rpc.ListRpcResponse"
    "service_name"
    "method_name"
  }},
};

PROTOBUF_NOINLINE void ListRpcResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:com.rpc.ListRpcResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.service_name_.Clear();
  _impl_.method_name_.Clear();
  _impl_.error_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ListRpcResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.rpc.ListRpcResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .com.rpc.ErrorCode error = 1;
  if (this->_internal_error() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_error(), target);
  }

  // repeated string service_name = 2;
  for (int i = 0, n = this->_internal_service_name_size(); i < n; ++i) {
    const auto& s = this->_internal_service_name().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.rpc.ListRpcResponse.service_name");
    target = stream->WriteString(2, s, target);
  }

  // repeated string method_name = 3;
  for (int i = 0, n = this->_internal_method_name_size(); i < n; ++i) {
    const auto& s = this->_internal_method_name().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.rpc.ListRpcResponse.method_name");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.rpc.ListRpcResponse)
  return target;
}

::size_t ListRpcResponse::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:com.rpc.ListRpcResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(
      reinterpret_cast<const void*>(this));
   {
    // repeated string service_name = 2;
     {
      total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_service_name().size());
      for (int i = 0, n = _internal_service_name().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            _internal_service_name().Get(i));
      }
    }
    // repeated string method_name = 3;
     {
      total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_method_name().size());
      for (int i = 0, n = _internal_method_name().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            _internal_method_name().Get(i));
      }
    }
  }
   {
    // .com.rpc.ErrorCode error = 1;
    if (this->_internal_error() != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_error());
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void ListRpcResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListRpcResponse*>(&to_msg);
  auto& from = static_cast<const ListRpcResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.rpc.ListRpcResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_service_name()->MergeFrom(from._internal_service_name());
  _this->_internal_mutable_method_name()->MergeFrom(from._internal_method_name());
  if (from._internal_error() != 0) {
    _this->_impl_.error_ = from._impl_.error_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListRpcResponse::CopyFrom(const ListRpcResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.rpc.ListRpcResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListRpcResponse::InternalSwap(ListRpcResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.service_name_.InternalSwap(&other->_impl_.service_name_);
  _impl_.method_name_.InternalSwap(&other->_impl_.method_name_);
  swap(_impl_.error_, other->_impl_.error_);
}

::google::protobuf::Metadata ListRpcResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetServiceRequest::_Internal {
 public:
};

GetServiceRequest::GetServiceRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.rpc.GetServiceRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetServiceRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::com::rpc::GetServiceRequest& from_msg)
      : service_name_(arena, from.service_name_),
        _cached_size_{0} {}

GetServiceRequest::GetServiceRequest(
    ::google::protobuf::Arena* arena,
    const GetServiceRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetServiceRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:com.rpc.GetServiceRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetServiceRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : service_name_(arena),
        _cached_size_{0} {}

inline void GetServiceRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetServiceRequest::~GetServiceRequest() {
  // @@protoc_insertion_point(destructor:com.rpc.GetServiceRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetServiceRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.service_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetServiceRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetServiceRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetServiceRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetServiceRequest>(),
            ::google::protobuf::Message::GetNewImpl<GetServiceRequest>(),
            ::google::protobuf::Message::GetClearImpl<GetServiceRequest>(),
                ::google::protobuf::Message::GetByteSizeLongImpl<GetServiceRequest>(),
                ::google::protobuf::Message::GetSerializeImpl<GetServiceRequest>(),
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetServiceRequest, _impl_._cached_size_),
            false,
        },
        &GetServiceRequest::kDescriptorMethods,
        &descriptor_table_rpc_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetServiceRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 46, 2> GetServiceRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::com::rpc::GetServiceRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string service_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetServiceRequest, _impl_.service_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string service_name = 1;
    {PROTOBUF_FIELD_OFFSET(GetServiceRequest, _impl_.service_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\14\0\0\0\0\0\0"
    "com.rpc.GetServiceRequest"
    "service_name"
  }},
};

PROTOBUF_NOINLINE void GetServiceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:com.rpc.GetServiceRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.service_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetServiceRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.rpc.GetServiceRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string service_name = 1;
  if (!this->_internal_service_name().empty()) {
    const std::string& _s = this->_internal_service_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.rpc.GetServiceRequest.service_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.rpc.GetServiceRequest)
  return target;
}

::size_t GetServiceRequest::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:com.rpc.GetServiceRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string service_name = 1;
    if (!this->_internal_service_name().empty()) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_service_name());
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void GetServiceRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetServiceRequest*>(&to_msg);
  auto& from = static_cast<const GetServiceRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.rpc.GetServiceRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_service_name().empty()) {
    _this->_internal_set_service_name(from._internal_service_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetServiceRequest::CopyFrom(const GetServiceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.rpc.GetServiceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetServiceRequest::InternalSwap(GetServiceRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.service_name_, &other->_impl_.service_name_, arena);
}

::google::protobuf::Metadata GetServiceRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetServiceResponse::_Internal {
 public:
};

GetServiceResponse::GetServiceResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.rpc.GetServiceResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetServiceResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::com::rpc::GetServiceResponse& from_msg)
      : proto_file_{visibility, arena, from.proto_file_},
        proto_file_name_{visibility, arena, from.proto_file_name_},
        _cached_size_{0} {}

GetServiceResponse::GetServiceResponse(
    ::google::protobuf::Arena* arena,
    const GetServiceResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetServiceResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.error_ = from._impl_.error_;

  // @@protoc_insertion_point(copy_constructor:com.rpc.GetServiceResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetServiceResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : proto_file_{visibility, arena},
        proto_file_name_{visibility, arena},
        _cached_size_{0} {}

inline void GetServiceResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.error_ = {};
}
GetServiceResponse::~GetServiceResponse() {
  // @@protoc_insertion_point(destructor:com.rpc.GetServiceResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetServiceResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetServiceResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetServiceResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetServiceResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetServiceResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetServiceResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetServiceResponse>(),
                ::google::protobuf::Message::GetByteSizeLongImpl<GetServiceResponse>(),
                ::google::protobuf::Message::GetSerializeImpl<GetServiceResponse>(),
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetServiceResponse, _impl_._cached_size_),
            false,
        },
        &GetServiceResponse::kDescriptorMethods,
        &descriptor_table_rpc_5fservice_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetServiceResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 60, 2> GetServiceResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::com::rpc::GetServiceResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .com.rpc.ErrorCode error = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetServiceResponse, _impl_.error_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetServiceResponse, _impl_.error_)}},
    // repeated string proto_file = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GetServiceResponse, _impl_.proto_file_)}},
    // repeated string proto_file_name = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(GetServiceResponse, _impl_.proto_file_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .com.rpc.ErrorCode error = 1;
    {PROTOBUF_FIELD_OFFSET(GetServiceResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated string proto_file = 2;
    {PROTOBUF_FIELD_OFFSET(GetServiceResponse, _impl_.proto_file_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string proto_file_name = 3;
    {PROTOBUF_FIELD_OFFSET(GetServiceResponse, _impl_.proto_file_name_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\32\0\12\17\0\0\0\0"
    "com.rpc.GetServiceResponse"
    "proto_file"
    "proto_file_name"
  }},
};

PROTOBUF_NOINLINE void GetServiceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:com.rpc.GetServiceResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.proto_file_.Clear();
  _impl_.proto_file_name_.Clear();
  _impl_.error_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetServiceResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.rpc.GetServiceResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .com.rpc.ErrorCode error = 1;
  if (this->_internal_error() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_error(), target);
  }

  // repeated string proto_file = 2;
  for (int i = 0, n = this->_internal_proto_file_size(); i < n; ++i) {
    const auto& s = this->_internal_proto_file().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.rpc.GetServiceResponse.proto_file");
    target = stream->WriteString(2, s, target);
  }

  // repeated string proto_file_name = 3;
  for (int i = 0, n = this->_internal_proto_file_name_size(); i < n; ++i) {
    const auto& s = this->_internal_proto_file_name().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.rpc.GetServiceResponse.proto_file_name");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.rpc.GetServiceResponse)
  return target;
}

::size_t GetServiceResponse::ByteSizeLong() const {
  // @@protoc_insertion_point(message_byte_size_start:com.rpc.GetServiceResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(
      reinterpret_cast<const void*>(this));
   {
    // repeated string proto_file = 2;
     {
      total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_proto_file().size());
      for (int i = 0, n = _internal_proto_file().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            _internal_proto_file().Get(i));
      }
    }
    // repeated string proto_file_name = 3;
     {
      total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_proto_file_name().size());
      for (int i = 0, n = _internal_proto_file_name().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            _internal_proto_file_name().Get(i));
      }
    }
  }
   {
    // .com.rpc.ErrorCode error = 1;
    if (this->_internal_error() != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_error());
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

void GetServiceResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetServiceResponse*>(&to_msg);
  auto& from = static_cast<const GetServiceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.rpc.GetServiceResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_proto_file()->MergeFrom(from._internal_proto_file());
  _this->_internal_mutable_proto_file_name()->MergeFrom(from._internal_proto_file_name());
  if (from._internal_error() != 0) {
    _this->_impl_.error_ = from._impl_.error_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetServiceResponse::CopyFrom(const GetServiceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.rpc.GetServiceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetServiceResponse::InternalSwap(GetServiceResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.proto_file_.InternalSwap(&other->_impl_.proto_file_);
  _impl_.proto_file_name_.InternalSwap(&other->_impl_.proto_file_name_);
  swap(_impl_.error_, other->_impl_.error_);
}

::google::protobuf::Metadata GetServiceResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

const ::google::protobuf::ServiceDescriptor* RpcService::descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_rpc_5fservice_2eproto);
  return file_level_service_descriptors_rpc_5fservice_2eproto[0];
}

const ::google::protobuf::ServiceDescriptor* RpcService::GetDescriptor() {
  return descriptor();
}

void RpcService::listRpc(::google::protobuf::RpcController* controller,
                         const ::com::rpc::ListRpcRequest*, ::com::rpc::ListRpcResponse*, ::google::protobuf::Closure* done) {
  controller->SetFailed("Method listRpc() not implemented.");
  done->Run();
}
void RpcService::getService(::google::protobuf::RpcController* controller,
                         const ::com::rpc::GetServiceRequest*, ::com::rpc::GetServiceResponse*, ::google::protobuf::Closure* done) {
  controller->SetFailed("Method getService() not implemented.");
  done->Run();
}

void RpcService::CallMethod(
    const ::google::protobuf::MethodDescriptor* method,
    ::google::protobuf::RpcController* controller,
    const ::google::protobuf::Message* request,
    ::google::protobuf::Message* response, ::google::protobuf::Closure* done) {
  ABSL_DCHECK_EQ(method->service(), file_level_service_descriptors_rpc_5fservice_2eproto[0]);
  switch (method->index()) {
    case 0:
      listRpc(controller, ::google::protobuf::DownCastMessage<::com::rpc::ListRpcRequest>(request),
             ::google::protobuf::DownCastMessage<::com::rpc::ListRpcResponse>(response), done);
      break;
    case 1:
      getService(controller, ::google::protobuf::DownCastMessage<::com::rpc::GetServiceRequest>(request),
             ::google::protobuf::DownCastMessage<::com::rpc::GetServiceResponse>(response), done);
      break;

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& RpcService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::com::rpc::ListRpcRequest::default_instance();
    case 1:
      return ::com::rpc::GetServiceRequest::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
                  ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& RpcService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::com::rpc::ListRpcResponse::default_instance();
    case 1:
      return ::com::rpc::GetServiceResponse::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
                  ->GetPrototype(method->output_type());
  }
}

RpcService_Stub::RpcService_Stub(::google::protobuf::RpcChannel* channel)
    : channel_(channel), owns_channel_(false) {}

RpcService_Stub::RpcService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
    : channel_(channel),
      owns_channel_(ownership ==
                    ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}

RpcService_Stub::~RpcService_Stub() {
  if (owns_channel_) delete channel_;
}

void RpcService_Stub::listRpc(::google::protobuf::RpcController* controller,
                              const ::com::rpc::ListRpcRequest* request,
                              ::com::rpc::ListRpcResponse* response, ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0), controller,
                       request, response, done);
}
void RpcService_Stub::getService(::google::protobuf::RpcController* controller,
                              const ::com::rpc::GetServiceRequest* request,
                              ::com::rpc::GetServiceResponse* response, ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1), controller,
                       request, response, done);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rpc
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rpc_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
