find_package(osadaptor REQUIRED)
if (osadaptor_FOUND)
    message(STATUS "OSAdaptor found")
endif ()
find_package(spdlog REQUIRED)
if (osadaptor_FOUND)
    message(STATUS "spdlog found")
endif ()
add_executable(ShmReaderSample ShmEndpointSample_1.cpp)
target_link_libraries(ShmReaderSample osadaptor spdlog)
add_executable(ShmWriterSample ShmEndpointSample_2.cpp)
target_link_libraries(ShmWriterSample osadaptor spdlog)