find_package(osadaptor REQUIRED)
if (osadaptor_FOUND)
    message(STATUS "OSAdaptor found")
endif ()
find_package(spdlog REQUIRED)
if (spdlog_FOUND)
    message(STATUS "spdlog found")
endif ()

add_executable(ShmReaderSample ShmReaderSample.cpp)
target_link_libraries(ShmReaderSample osadaptor spdlog)
add_executable(ShmWriterSample ShmWriterSample.cpp)
target_link_libraries(ShmWriterSample osadaptor spdlog)