// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_service.proto

#ifndef PROTOBUF_INCLUDED_rpc_5fservice_2eproto
#define PROTOBUF_INCLUDED_rpc_5fservice_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "rpc.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_rpc_5fservice_2eproto 

namespace protobuf_rpc_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_rpc_5fservice_2eproto
namespace com {
namespace rpc {
class GetServiceRequest;
class GetServiceRequestDefaultTypeInternal;
extern GetServiceRequestDefaultTypeInternal _GetServiceRequest_default_instance_;
class GetServiceResponse;
class GetServiceResponseDefaultTypeInternal;
extern GetServiceResponseDefaultTypeInternal _GetServiceResponse_default_instance_;
class ListRpcRequest;
class ListRpcRequestDefaultTypeInternal;
extern ListRpcRequestDefaultTypeInternal _ListRpcRequest_default_instance_;
class ListRpcResponse;
class ListRpcResponseDefaultTypeInternal;
extern ListRpcResponseDefaultTypeInternal _ListRpcResponse_default_instance_;
}  // namespace rpc
}  // namespace com
namespace google {
namespace protobuf {
template<> ::com::rpc::GetServiceRequest* Arena::CreateMaybeMessage<::com::rpc::GetServiceRequest>(Arena*);
template<> ::com::rpc::GetServiceResponse* Arena::CreateMaybeMessage<::com::rpc::GetServiceResponse>(Arena*);
template<> ::com::rpc::ListRpcRequest* Arena::CreateMaybeMessage<::com::rpc::ListRpcRequest>(Arena*);
template<> ::com::rpc::ListRpcResponse* Arena::CreateMaybeMessage<::com::rpc::ListRpcResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace com {
namespace rpc {

// ===================================================================

class ListRpcRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.rpc.ListRpcRequest) */ {
 public:
  ListRpcRequest();
  virtual ~ListRpcRequest();

  ListRpcRequest(const ListRpcRequest& from);

  inline ListRpcRequest& operator=(const ListRpcRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListRpcRequest(ListRpcRequest&& from) noexcept
    : ListRpcRequest() {
    *this = ::std::move(from);
  }

  inline ListRpcRequest& operator=(ListRpcRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ListRpcRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListRpcRequest* internal_default_instance() {
    return reinterpret_cast<const ListRpcRequest*>(
               &_ListRpcRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ListRpcRequest* other);
  friend void swap(ListRpcRequest& a, ListRpcRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListRpcRequest* New() const final {
    return CreateMaybeMessage<ListRpcRequest>(NULL);
  }

  ListRpcRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ListRpcRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ListRpcRequest& from);
  void MergeFrom(const ListRpcRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListRpcRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string service_name = 1;
  void clear_service_name();
  static const int kServiceNameFieldNumber = 1;
  const ::std::string& service_name() const;
  void set_service_name(const ::std::string& value);
  #if LANG_CXX11
  void set_service_name(::std::string&& value);
  #endif
  void set_service_name(const char* value);
  void set_service_name(const char* value, size_t size);
  ::std::string* mutable_service_name();
  ::std::string* release_service_name();
  void set_allocated_service_name(::std::string* service_name);

  // bool list_method = 2;
  void clear_list_method();
  static const int kListMethodFieldNumber = 2;
  bool list_method() const;
  void set_list_method(bool value);

  // @@protoc_insertion_point(class_scope:com.rpc.ListRpcRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr service_name_;
  bool list_method_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_rpc_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ListRpcResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.rpc.ListRpcResponse) */ {
 public:
  ListRpcResponse();
  virtual ~ListRpcResponse();

  ListRpcResponse(const ListRpcResponse& from);

  inline ListRpcResponse& operator=(const ListRpcResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListRpcResponse(ListRpcResponse&& from) noexcept
    : ListRpcResponse() {
    *this = ::std::move(from);
  }

  inline ListRpcResponse& operator=(ListRpcResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ListRpcResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListRpcResponse* internal_default_instance() {
    return reinterpret_cast<const ListRpcResponse*>(
               &_ListRpcResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ListRpcResponse* other);
  friend void swap(ListRpcResponse& a, ListRpcResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListRpcResponse* New() const final {
    return CreateMaybeMessage<ListRpcResponse>(NULL);
  }

  ListRpcResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ListRpcResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ListRpcResponse& from);
  void MergeFrom(const ListRpcResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListRpcResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string service_name = 2;
  int service_name_size() const;
  void clear_service_name();
  static const int kServiceNameFieldNumber = 2;
  const ::std::string& service_name(int index) const;
  ::std::string* mutable_service_name(int index);
  void set_service_name(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_service_name(int index, ::std::string&& value);
  #endif
  void set_service_name(int index, const char* value);
  void set_service_name(int index, const char* value, size_t size);
  ::std::string* add_service_name();
  void add_service_name(const ::std::string& value);
  #if LANG_CXX11
  void add_service_name(::std::string&& value);
  #endif
  void add_service_name(const char* value);
  void add_service_name(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& service_name() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_service_name();

  // repeated string method_name = 3;
  int method_name_size() const;
  void clear_method_name();
  static const int kMethodNameFieldNumber = 3;
  const ::std::string& method_name(int index) const;
  ::std::string* mutable_method_name(int index);
  void set_method_name(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_method_name(int index, ::std::string&& value);
  #endif
  void set_method_name(int index, const char* value);
  void set_method_name(int index, const char* value, size_t size);
  ::std::string* add_method_name();
  void add_method_name(const ::std::string& value);
  #if LANG_CXX11
  void add_method_name(::std::string&& value);
  #endif
  void add_method_name(const char* value);
  void add_method_name(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& method_name() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_method_name();

  // .com.rpc.ErrorCode error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  ::com::rpc::ErrorCode error() const;
  void set_error(::com::rpc::ErrorCode value);

  // @@protoc_insertion_point(class_scope:com.rpc.ListRpcResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> service_name_;
  ::google::protobuf::RepeatedPtrField< ::std::string> method_name_;
  int error_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_rpc_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetServiceRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.rpc.GetServiceRequest) */ {
 public:
  GetServiceRequest();
  virtual ~GetServiceRequest();

  GetServiceRequest(const GetServiceRequest& from);

  inline GetServiceRequest& operator=(const GetServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetServiceRequest(GetServiceRequest&& from) noexcept
    : GetServiceRequest() {
    *this = ::std::move(from);
  }

  inline GetServiceRequest& operator=(GetServiceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetServiceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetServiceRequest* internal_default_instance() {
    return reinterpret_cast<const GetServiceRequest*>(
               &_GetServiceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GetServiceRequest* other);
  friend void swap(GetServiceRequest& a, GetServiceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetServiceRequest* New() const final {
    return CreateMaybeMessage<GetServiceRequest>(NULL);
  }

  GetServiceRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetServiceRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetServiceRequest& from);
  void MergeFrom(const GetServiceRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetServiceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string service_name = 1;
  void clear_service_name();
  static const int kServiceNameFieldNumber = 1;
  const ::std::string& service_name() const;
  void set_service_name(const ::std::string& value);
  #if LANG_CXX11
  void set_service_name(::std::string&& value);
  #endif
  void set_service_name(const char* value);
  void set_service_name(const char* value, size_t size);
  ::std::string* mutable_service_name();
  ::std::string* release_service_name();
  void set_allocated_service_name(::std::string* service_name);

  // @@protoc_insertion_point(class_scope:com.rpc.GetServiceRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr service_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_rpc_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetServiceResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.rpc.GetServiceResponse) */ {
 public:
  GetServiceResponse();
  virtual ~GetServiceResponse();

  GetServiceResponse(const GetServiceResponse& from);

  inline GetServiceResponse& operator=(const GetServiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetServiceResponse(GetServiceResponse&& from) noexcept
    : GetServiceResponse() {
    *this = ::std::move(from);
  }

  inline GetServiceResponse& operator=(GetServiceResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetServiceResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetServiceResponse* internal_default_instance() {
    return reinterpret_cast<const GetServiceResponse*>(
               &_GetServiceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(GetServiceResponse* other);
  friend void swap(GetServiceResponse& a, GetServiceResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetServiceResponse* New() const final {
    return CreateMaybeMessage<GetServiceResponse>(NULL);
  }

  GetServiceResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetServiceResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetServiceResponse& from);
  void MergeFrom(const GetServiceResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetServiceResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string proto_file = 2;
  int proto_file_size() const;
  void clear_proto_file();
  static const int kProtoFileFieldNumber = 2;
  const ::std::string& proto_file(int index) const;
  ::std::string* mutable_proto_file(int index);
  void set_proto_file(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_proto_file(int index, ::std::string&& value);
  #endif
  void set_proto_file(int index, const char* value);
  void set_proto_file(int index, const char* value, size_t size);
  ::std::string* add_proto_file();
  void add_proto_file(const ::std::string& value);
  #if LANG_CXX11
  void add_proto_file(::std::string&& value);
  #endif
  void add_proto_file(const char* value);
  void add_proto_file(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& proto_file() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_proto_file();

  // repeated string proto_file_name = 3;
  int proto_file_name_size() const;
  void clear_proto_file_name();
  static const int kProtoFileNameFieldNumber = 3;
  const ::std::string& proto_file_name(int index) const;
  ::std::string* mutable_proto_file_name(int index);
  void set_proto_file_name(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_proto_file_name(int index, ::std::string&& value);
  #endif
  void set_proto_file_name(int index, const char* value);
  void set_proto_file_name(int index, const char* value, size_t size);
  ::std::string* add_proto_file_name();
  void add_proto_file_name(const ::std::string& value);
  #if LANG_CXX11
  void add_proto_file_name(::std::string&& value);
  #endif
  void add_proto_file_name(const char* value);
  void add_proto_file_name(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& proto_file_name() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_proto_file_name();

  // .com.rpc.ErrorCode error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  ::com::rpc::ErrorCode error() const;
  void set_error(::com::rpc::ErrorCode value);

  // @@protoc_insertion_point(class_scope:com.rpc.GetServiceResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> proto_file_;
  ::google::protobuf::RepeatedPtrField< ::std::string> proto_file_name_;
  int error_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_rpc_5fservice_2eproto::TableStruct;
};
// ===================================================================

class RpcService_Stub;

class RpcService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline RpcService() {};
 public:
  virtual ~RpcService();

  typedef RpcService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void listRpc(::google::protobuf::RpcController* controller,
                       const ::com::rpc::ListRpcRequest* request,
                       ::com::rpc::ListRpcResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void getService(::google::protobuf::RpcController* controller,
                       const ::com::rpc::GetServiceRequest* request,
                       ::com::rpc::GetServiceResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RpcService);
};

class RpcService_Stub : public RpcService {
 public:
  RpcService_Stub(::google::protobuf::RpcChannel* channel);
  RpcService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~RpcService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements RpcService ------------------------------------------

  void listRpc(::google::protobuf::RpcController* controller,
                       const ::com::rpc::ListRpcRequest* request,
                       ::com::rpc::ListRpcResponse* response,
                       ::google::protobuf::Closure* done);
  void getService(::google::protobuf::RpcController* controller,
                       const ::com::rpc::GetServiceRequest* request,
                       ::com::rpc::GetServiceResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RpcService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ListRpcRequest

// string service_name = 1;
inline void ListRpcRequest::clear_service_name() {
  service_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ListRpcRequest::service_name() const {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcRequest.service_name)
  return service_name_.GetNoArena();
}
inline void ListRpcRequest::set_service_name(const ::std::string& value) {
  
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcRequest.service_name)
}
#if LANG_CXX11
inline void ListRpcRequest::set_service_name(::std::string&& value) {
  
  service_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.rpc.ListRpcRequest.service_name)
}
#endif
inline void ListRpcRequest::set_service_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.rpc.ListRpcRequest.service_name)
}
inline void ListRpcRequest::set_service_name(const char* value, size_t size) {
  
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.rpc.ListRpcRequest.service_name)
}
inline ::std::string* ListRpcRequest::mutable_service_name() {
  
  // @@protoc_insertion_point(field_mutable:com.rpc.ListRpcRequest.service_name)
  return service_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ListRpcRequest::release_service_name() {
  // @@protoc_insertion_point(field_release:com.rpc.ListRpcRequest.service_name)
  
  return service_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListRpcRequest::set_allocated_service_name(::std::string* service_name) {
  if (service_name != NULL) {
    
  } else {
    
  }
  service_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), service_name);
  // @@protoc_insertion_point(field_set_allocated:com.rpc.ListRpcRequest.service_name)
}

// bool list_method = 2;
inline void ListRpcRequest::clear_list_method() {
  list_method_ = false;
}
inline bool ListRpcRequest::list_method() const {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcRequest.list_method)
  return list_method_;
}
inline void ListRpcRequest::set_list_method(bool value) {
  
  list_method_ = value;
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcRequest.list_method)
}

// -------------------------------------------------------------------

// ListRpcResponse

// .com.rpc.ErrorCode error = 1;
inline void ListRpcResponse::clear_error() {
  error_ = 0;
}
inline ::com::rpc::ErrorCode ListRpcResponse::error() const {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcResponse.error)
  return static_cast< ::com::rpc::ErrorCode >(error_);
}
inline void ListRpcResponse::set_error(::com::rpc::ErrorCode value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcResponse.error)
}

// repeated string service_name = 2;
inline int ListRpcResponse::service_name_size() const {
  return service_name_.size();
}
inline void ListRpcResponse::clear_service_name() {
  service_name_.Clear();
}
inline const ::std::string& ListRpcResponse::service_name(int index) const {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcResponse.service_name)
  return service_name_.Get(index);
}
inline ::std::string* ListRpcResponse::mutable_service_name(int index) {
  // @@protoc_insertion_point(field_mutable:com.rpc.ListRpcResponse.service_name)
  return service_name_.Mutable(index);
}
inline void ListRpcResponse::set_service_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcResponse.service_name)
  service_name_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ListRpcResponse::set_service_name(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcResponse.service_name)
  service_name_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ListRpcResponse::set_service_name(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  service_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:com.rpc.ListRpcResponse.service_name)
}
inline void ListRpcResponse::set_service_name(int index, const char* value, size_t size) {
  service_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.rpc.ListRpcResponse.service_name)
}
inline ::std::string* ListRpcResponse::add_service_name() {
  // @@protoc_insertion_point(field_add_mutable:com.rpc.ListRpcResponse.service_name)
  return service_name_.Add();
}
inline void ListRpcResponse::add_service_name(const ::std::string& value) {
  service_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:com.rpc.ListRpcResponse.service_name)
}
#if LANG_CXX11
inline void ListRpcResponse::add_service_name(::std::string&& value) {
  service_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:com.rpc.ListRpcResponse.service_name)
}
#endif
inline void ListRpcResponse::add_service_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  service_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:com.rpc.ListRpcResponse.service_name)
}
inline void ListRpcResponse::add_service_name(const char* value, size_t size) {
  service_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:com.rpc.ListRpcResponse.service_name)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListRpcResponse::service_name() const {
  // @@protoc_insertion_point(field_list:com.rpc.ListRpcResponse.service_name)
  return service_name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ListRpcResponse::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable_list:com.rpc.ListRpcResponse.service_name)
  return &service_name_;
}

// repeated string method_name = 3;
inline int ListRpcResponse::method_name_size() const {
  return method_name_.size();
}
inline void ListRpcResponse::clear_method_name() {
  method_name_.Clear();
}
inline const ::std::string& ListRpcResponse::method_name(int index) const {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcResponse.method_name)
  return method_name_.Get(index);
}
inline ::std::string* ListRpcResponse::mutable_method_name(int index) {
  // @@protoc_insertion_point(field_mutable:com.rpc.ListRpcResponse.method_name)
  return method_name_.Mutable(index);
}
inline void ListRpcResponse::set_method_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcResponse.method_name)
  method_name_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ListRpcResponse::set_method_name(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcResponse.method_name)
  method_name_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ListRpcResponse::set_method_name(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  method_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:com.rpc.ListRpcResponse.method_name)
}
inline void ListRpcResponse::set_method_name(int index, const char* value, size_t size) {
  method_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.rpc.ListRpcResponse.method_name)
}
inline ::std::string* ListRpcResponse::add_method_name() {
  // @@protoc_insertion_point(field_add_mutable:com.rpc.ListRpcResponse.method_name)
  return method_name_.Add();
}
inline void ListRpcResponse::add_method_name(const ::std::string& value) {
  method_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:com.rpc.ListRpcResponse.method_name)
}
#if LANG_CXX11
inline void ListRpcResponse::add_method_name(::std::string&& value) {
  method_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:com.rpc.ListRpcResponse.method_name)
}
#endif
inline void ListRpcResponse::add_method_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  method_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:com.rpc.ListRpcResponse.method_name)
}
inline void ListRpcResponse::add_method_name(const char* value, size_t size) {
  method_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:com.rpc.ListRpcResponse.method_name)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListRpcResponse::method_name() const {
  // @@protoc_insertion_point(field_list:com.rpc.ListRpcResponse.method_name)
  return method_name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ListRpcResponse::mutable_method_name() {
  // @@protoc_insertion_point(field_mutable_list:com.rpc.ListRpcResponse.method_name)
  return &method_name_;
}

// -------------------------------------------------------------------

// GetServiceRequest

// string service_name = 1;
inline void GetServiceRequest::clear_service_name() {
  service_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetServiceRequest::service_name() const {
  // @@protoc_insertion_point(field_get:com.rpc.GetServiceRequest.service_name)
  return service_name_.GetNoArena();
}
inline void GetServiceRequest::set_service_name(const ::std::string& value) {
  
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceRequest.service_name)
}
#if LANG_CXX11
inline void GetServiceRequest::set_service_name(::std::string&& value) {
  
  service_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.rpc.GetServiceRequest.service_name)
}
#endif
inline void GetServiceRequest::set_service_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.rpc.GetServiceRequest.service_name)
}
inline void GetServiceRequest::set_service_name(const char* value, size_t size) {
  
  service_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.rpc.GetServiceRequest.service_name)
}
inline ::std::string* GetServiceRequest::mutable_service_name() {
  
  // @@protoc_insertion_point(field_mutable:com.rpc.GetServiceRequest.service_name)
  return service_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetServiceRequest::release_service_name() {
  // @@protoc_insertion_point(field_release:com.rpc.GetServiceRequest.service_name)
  
  return service_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetServiceRequest::set_allocated_service_name(::std::string* service_name) {
  if (service_name != NULL) {
    
  } else {
    
  }
  service_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), service_name);
  // @@protoc_insertion_point(field_set_allocated:com.rpc.GetServiceRequest.service_name)
}

// -------------------------------------------------------------------

// GetServiceResponse

// .com.rpc.ErrorCode error = 1;
inline void GetServiceResponse::clear_error() {
  error_ = 0;
}
inline ::com::rpc::ErrorCode GetServiceResponse::error() const {
  // @@protoc_insertion_point(field_get:com.rpc.GetServiceResponse.error)
  return static_cast< ::com::rpc::ErrorCode >(error_);
}
inline void GetServiceResponse::set_error(::com::rpc::ErrorCode value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceResponse.error)
}

// repeated string proto_file = 2;
inline int GetServiceResponse::proto_file_size() const {
  return proto_file_.size();
}
inline void GetServiceResponse::clear_proto_file() {
  proto_file_.Clear();
}
inline const ::std::string& GetServiceResponse::proto_file(int index) const {
  // @@protoc_insertion_point(field_get:com.rpc.GetServiceResponse.proto_file)
  return proto_file_.Get(index);
}
inline ::std::string* GetServiceResponse::mutable_proto_file(int index) {
  // @@protoc_insertion_point(field_mutable:com.rpc.GetServiceResponse.proto_file)
  return proto_file_.Mutable(index);
}
inline void GetServiceResponse::set_proto_file(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceResponse.proto_file)
  proto_file_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void GetServiceResponse::set_proto_file(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceResponse.proto_file)
  proto_file_.Mutable(index)->assign(std::move(value));
}
#endif
inline void GetServiceResponse::set_proto_file(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  proto_file_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:com.rpc.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::set_proto_file(int index, const char* value, size_t size) {
  proto_file_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.rpc.GetServiceResponse.proto_file)
}
inline ::std::string* GetServiceResponse::add_proto_file() {
  // @@protoc_insertion_point(field_add_mutable:com.rpc.GetServiceResponse.proto_file)
  return proto_file_.Add();
}
inline void GetServiceResponse::add_proto_file(const ::std::string& value) {
  proto_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:com.rpc.GetServiceResponse.proto_file)
}
#if LANG_CXX11
inline void GetServiceResponse::add_proto_file(::std::string&& value) {
  proto_file_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:com.rpc.GetServiceResponse.proto_file)
}
#endif
inline void GetServiceResponse::add_proto_file(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  proto_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:com.rpc.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::add_proto_file(const char* value, size_t size) {
  proto_file_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:com.rpc.GetServiceResponse.proto_file)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
GetServiceResponse::proto_file() const {
  // @@protoc_insertion_point(field_list:com.rpc.GetServiceResponse.proto_file)
  return proto_file_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
GetServiceResponse::mutable_proto_file() {
  // @@protoc_insertion_point(field_mutable_list:com.rpc.GetServiceResponse.proto_file)
  return &proto_file_;
}

// repeated string proto_file_name = 3;
inline int GetServiceResponse::proto_file_name_size() const {
  return proto_file_name_.size();
}
inline void GetServiceResponse::clear_proto_file_name() {
  proto_file_name_.Clear();
}
inline const ::std::string& GetServiceResponse::proto_file_name(int index) const {
  // @@protoc_insertion_point(field_get:com.rpc.GetServiceResponse.proto_file_name)
  return proto_file_name_.Get(index);
}
inline ::std::string* GetServiceResponse::mutable_proto_file_name(int index) {
  // @@protoc_insertion_point(field_mutable:com.rpc.GetServiceResponse.proto_file_name)
  return proto_file_name_.Mutable(index);
}
inline void GetServiceResponse::set_proto_file_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceResponse.proto_file_name)
  proto_file_name_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void GetServiceResponse::set_proto_file_name(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceResponse.proto_file_name)
  proto_file_name_.Mutable(index)->assign(std::move(value));
}
#endif
inline void GetServiceResponse::set_proto_file_name(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  proto_file_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:com.rpc.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::set_proto_file_name(int index, const char* value, size_t size) {
  proto_file_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.rpc.GetServiceResponse.proto_file_name)
}
inline ::std::string* GetServiceResponse::add_proto_file_name() {
  // @@protoc_insertion_point(field_add_mutable:com.rpc.GetServiceResponse.proto_file_name)
  return proto_file_name_.Add();
}
inline void GetServiceResponse::add_proto_file_name(const ::std::string& value) {
  proto_file_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:com.rpc.GetServiceResponse.proto_file_name)
}
#if LANG_CXX11
inline void GetServiceResponse::add_proto_file_name(::std::string&& value) {
  proto_file_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:com.rpc.GetServiceResponse.proto_file_name)
}
#endif
inline void GetServiceResponse::add_proto_file_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  proto_file_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:com.rpc.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::add_proto_file_name(const char* value, size_t size) {
  proto_file_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:com.rpc.GetServiceResponse.proto_file_name)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
GetServiceResponse::proto_file_name() const {
  // @@protoc_insertion_point(field_list:com.rpc.GetServiceResponse.proto_file_name)
  return proto_file_name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
GetServiceResponse::mutable_proto_file_name() {
  // @@protoc_insertion_point(field_mutable_list:com.rpc.GetServiceResponse.proto_file_name)
  return &proto_file_name_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_rpc_5fservice_2eproto
