// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc_service.proto
// Protobuf C++ Version: 5.28.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpc_5fservice_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_rpc_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/service.h"
#include "google/protobuf/unknown_field_set.h"
#include "rpc.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rpc_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_rpc_5fservice_2eproto;
namespace com {
namespace rpc {
class GetServiceRequest;
struct GetServiceRequestDefaultTypeInternal;
extern GetServiceRequestDefaultTypeInternal _GetServiceRequest_default_instance_;
class GetServiceResponse;
struct GetServiceResponseDefaultTypeInternal;
extern GetServiceResponseDefaultTypeInternal _GetServiceResponse_default_instance_;
class ListRpcRequest;
struct ListRpcRequestDefaultTypeInternal;
extern ListRpcRequestDefaultTypeInternal _ListRpcRequest_default_instance_;
class ListRpcResponse;
struct ListRpcResponseDefaultTypeInternal;
extern ListRpcResponseDefaultTypeInternal _ListRpcResponse_default_instance_;
}  // namespace rpc
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace com {
namespace rpc {

// ===================================================================


// -------------------------------------------------------------------

class ListRpcResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:com.rpc.ListRpcResponse) */ {
 public:
  inline ListRpcResponse() : ListRpcResponse(nullptr) {}
  ~ListRpcResponse() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListRpcResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ListRpcResponse(const ListRpcResponse& from) : ListRpcResponse(nullptr, from) {}
  inline ListRpcResponse(ListRpcResponse&& from) noexcept
      : ListRpcResponse(nullptr, std::move(from)) {}
  inline ListRpcResponse& operator=(const ListRpcResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListRpcResponse& operator=(ListRpcResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListRpcResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListRpcResponse* internal_default_instance() {
    return reinterpret_cast<const ListRpcResponse*>(
        &_ListRpcResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ListRpcResponse& a, ListRpcResponse& b) { a.Swap(&b); }
  inline void Swap(ListRpcResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListRpcResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListRpcResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ListRpcResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListRpcResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListRpcResponse& from) { ListRpcResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ListRpcResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "com.rpc.ListRpcResponse"; }

 protected:
  explicit ListRpcResponse(::google::protobuf::Arena* arena);
  ListRpcResponse(::google::protobuf::Arena* arena, const ListRpcResponse& from);
  ListRpcResponse(::google::protobuf::Arena* arena, ListRpcResponse&& from) noexcept
      : ListRpcResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServiceNameFieldNumber = 2,
    kMethodNameFieldNumber = 3,
    kErrorFieldNumber = 1,
  };
  // repeated string service_name = 2;
  int service_name_size() const;
  private:
  int _internal_service_name_size() const;

  public:
  void clear_service_name() ;
  const std::string& service_name(int index) const;
  std::string* mutable_service_name(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_service_name(int index, Arg_&& value, Args_... args);
  std::string* add_service_name();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_service_name(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& service_name() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_service_name();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_service_name() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_service_name();

  public:
  // repeated string method_name = 3;
  int method_name_size() const;
  private:
  int _internal_method_name_size() const;

  public:
  void clear_method_name() ;
  const std::string& method_name(int index) const;
  std::string* mutable_method_name(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_method_name(int index, Arg_&& value, Args_... args);
  std::string* add_method_name();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_method_name(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& method_name() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_method_name();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_method_name() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_method_name();

  public:
  // .com.rpc.ErrorCode error = 1;
  void clear_error() ;
  ::com::rpc::ErrorCode error() const;
  void set_error(::com::rpc::ErrorCode value);

  private:
  ::com::rpc::ErrorCode _internal_error() const;
  void _internal_set_error(::com::rpc::ErrorCode value);

  public:
  // @@protoc_insertion_point(class_scope:com.rpc.ListRpcResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      55, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ListRpcResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ListRpcResponse& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> service_name_;
    ::google::protobuf::RepeatedPtrField<std::string> method_name_;
    int error_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ListRpcRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:com.rpc.ListRpcRequest) */ {
 public:
  inline ListRpcRequest() : ListRpcRequest(nullptr) {}
  ~ListRpcRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ListRpcRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ListRpcRequest(const ListRpcRequest& from) : ListRpcRequest(nullptr, from) {}
  inline ListRpcRequest(ListRpcRequest&& from) noexcept
      : ListRpcRequest(nullptr, std::move(from)) {}
  inline ListRpcRequest& operator=(const ListRpcRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListRpcRequest& operator=(ListRpcRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListRpcRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListRpcRequest* internal_default_instance() {
    return reinterpret_cast<const ListRpcRequest*>(
        &_ListRpcRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ListRpcRequest& a, ListRpcRequest& b) { a.Swap(&b); }
  inline void Swap(ListRpcRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListRpcRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListRpcRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ListRpcRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ListRpcRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ListRpcRequest& from) { ListRpcRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ListRpcRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "com.rpc.ListRpcRequest"; }

 protected:
  explicit ListRpcRequest(::google::protobuf::Arena* arena);
  ListRpcRequest(::google::protobuf::Arena* arena, const ListRpcRequest& from);
  ListRpcRequest(::google::protobuf::Arena* arena, ListRpcRequest&& from) noexcept
      : ListRpcRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServiceNameFieldNumber = 1,
    kListMethodFieldNumber = 2,
  };
  // string service_name = 1;
  void clear_service_name() ;
  const std::string& service_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_service_name(Arg_&& arg, Args_... args);
  std::string* mutable_service_name();
  PROTOBUF_NODISCARD std::string* release_service_name();
  void set_allocated_service_name(std::string* value);

  private:
  const std::string& _internal_service_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_name(
      const std::string& value);
  std::string* _internal_mutable_service_name();

  public:
  // bool list_method = 2;
  void clear_list_method() ;
  bool list_method() const;
  void set_list_method(bool value);

  private:
  bool _internal_list_method() const;
  void _internal_set_list_method(bool value);

  public:
  // @@protoc_insertion_point(class_scope:com.rpc.ListRpcRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      43, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ListRpcRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ListRpcRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr service_name_;
    bool list_method_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetServiceResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:com.rpc.GetServiceResponse) */ {
 public:
  inline GetServiceResponse() : GetServiceResponse(nullptr) {}
  ~GetServiceResponse() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetServiceResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetServiceResponse(const GetServiceResponse& from) : GetServiceResponse(nullptr, from) {}
  inline GetServiceResponse(GetServiceResponse&& from) noexcept
      : GetServiceResponse(nullptr, std::move(from)) {}
  inline GetServiceResponse& operator=(const GetServiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServiceResponse& operator=(GetServiceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServiceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServiceResponse* internal_default_instance() {
    return reinterpret_cast<const GetServiceResponse*>(
        &_GetServiceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(GetServiceResponse& a, GetServiceResponse& b) { a.Swap(&b); }
  inline void Swap(GetServiceResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServiceResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServiceResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<GetServiceResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetServiceResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetServiceResponse& from) { GetServiceResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetServiceResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "com.rpc.GetServiceResponse"; }

 protected:
  explicit GetServiceResponse(::google::protobuf::Arena* arena);
  GetServiceResponse(::google::protobuf::Arena* arena, const GetServiceResponse& from);
  GetServiceResponse(::google::protobuf::Arena* arena, GetServiceResponse&& from) noexcept
      : GetServiceResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kProtoFileFieldNumber = 2,
    kProtoFileNameFieldNumber = 3,
    kErrorFieldNumber = 1,
  };
  // repeated string proto_file = 2;
  int proto_file_size() const;
  private:
  int _internal_proto_file_size() const;

  public:
  void clear_proto_file() ;
  const std::string& proto_file(int index) const;
  std::string* mutable_proto_file(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_proto_file(int index, Arg_&& value, Args_... args);
  std::string* add_proto_file();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_proto_file(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& proto_file() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_proto_file();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_proto_file() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_proto_file();

  public:
  // repeated string proto_file_name = 3;
  int proto_file_name_size() const;
  private:
  int _internal_proto_file_name_size() const;

  public:
  void clear_proto_file_name() ;
  const std::string& proto_file_name(int index) const;
  std::string* mutable_proto_file_name(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_proto_file_name(int index, Arg_&& value, Args_... args);
  std::string* add_proto_file_name();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_proto_file_name(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& proto_file_name() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_proto_file_name();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_proto_file_name() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_proto_file_name();

  public:
  // .com.rpc.ErrorCode error = 1;
  void clear_error() ;
  ::com::rpc::ErrorCode error() const;
  void set_error(::com::rpc::ErrorCode value);

  private:
  ::com::rpc::ErrorCode _internal_error() const;
  void _internal_set_error(::com::rpc::ErrorCode value);

  public:
  // @@protoc_insertion_point(class_scope:com.rpc.GetServiceResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      60, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetServiceResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetServiceResponse& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> proto_file_;
    ::google::protobuf::RepeatedPtrField<std::string> proto_file_name_;
    int error_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetServiceRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:com.rpc.GetServiceRequest) */ {
 public:
  inline GetServiceRequest() : GetServiceRequest(nullptr) {}
  ~GetServiceRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetServiceRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetServiceRequest(const GetServiceRequest& from) : GetServiceRequest(nullptr, from) {}
  inline GetServiceRequest(GetServiceRequest&& from) noexcept
      : GetServiceRequest(nullptr, std::move(from)) {}
  inline GetServiceRequest& operator=(const GetServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServiceRequest& operator=(GetServiceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServiceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServiceRequest* internal_default_instance() {
    return reinterpret_cast<const GetServiceRequest*>(
        &_GetServiceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GetServiceRequest& a, GetServiceRequest& b) { a.Swap(&b); }
  inline void Swap(GetServiceRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServiceRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServiceRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<GetServiceRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetServiceRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetServiceRequest& from) { GetServiceRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  ::size_t ByteSizeLong() const PROTOBUF_FINAL;
  ::uint8_t* _InternalSerialize(::uint8_t* target,
                              ::google::protobuf::io::EpsCopyOutputStream*
                                  stream) const PROTOBUF_FINAL;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetServiceRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "com.rpc.GetServiceRequest"; }

 protected:
  explicit GetServiceRequest(::google::protobuf::Arena* arena);
  GetServiceRequest(::google::protobuf::Arena* arena, const GetServiceRequest& from);
  GetServiceRequest(::google::protobuf::Arena* arena, GetServiceRequest&& from) noexcept
      : GetServiceRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServiceNameFieldNumber = 1,
  };
  // string service_name = 1;
  void clear_service_name() ;
  const std::string& service_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_service_name(Arg_&& arg, Args_... args);
  std::string* mutable_service_name();
  PROTOBUF_NODISCARD std::string* release_service_name();
  void set_allocated_service_name(std::string* value);

  private:
  const std::string& _internal_service_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_name(
      const std::string& value);
  std::string* _internal_mutable_service_name();

  public:
  // @@protoc_insertion_point(class_scope:com.rpc.GetServiceRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      46, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetServiceRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetServiceRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr service_name_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_5fservice_2eproto;
};

// ===================================================================


// -------------------------------------------------------------------

class RpcService_Stub;
class RpcService : public ::google::protobuf::Service {
 protected:
  RpcService() = default;

 public:
  using Stub = RpcService_Stub;

  RpcService(const RpcService&) = delete;
  RpcService& operator=(const RpcService&) = delete;
  virtual ~RpcService() = default;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void listRpc(::google::protobuf::RpcController* controller,
                        const ::com::rpc::ListRpcRequest* request,
                        ::com::rpc::ListRpcResponse* response,
                        ::google::protobuf::Closure* done);
  virtual void getService(::google::protobuf::RpcController* controller,
                        const ::com::rpc::GetServiceRequest* request,
                        ::com::rpc::GetServiceResponse* response,
                        ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------
  const ::google::protobuf::ServiceDescriptor* GetDescriptor() override;

  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done) override;

  const ::google::protobuf::Message& GetRequestPrototype(
      const ::google::protobuf::MethodDescriptor* method) const override;

  const ::google::protobuf::Message& GetResponsePrototype(
      const ::google::protobuf::MethodDescriptor* method) const override;
};

class RpcService_Stub final : public RpcService {
 public:
  RpcService_Stub(::google::protobuf::RpcChannel* channel);
  RpcService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);

  RpcService_Stub(const RpcService_Stub&) = delete;
  RpcService_Stub& operator=(const RpcService_Stub&) = delete;

  ~RpcService_Stub() override;

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements RpcService ------------------------------------------
  void listRpc(::google::protobuf::RpcController* controller,
                        const ::com::rpc::ListRpcRequest* request,
                        ::com::rpc::ListRpcResponse* response,
                        ::google::protobuf::Closure* done) override;
  void getService(::google::protobuf::RpcController* controller,
                        const ::com::rpc::GetServiceRequest* request,
                        ::com::rpc::GetServiceResponse* response,
                        ::google::protobuf::Closure* done) override;

 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
};
// ===================================================================



// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ListRpcRequest

// string service_name = 1;
inline void ListRpcRequest::clear_service_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.ClearToEmpty();
}
inline const std::string& ListRpcRequest::service_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcRequest.service_name)
  return _internal_service_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ListRpcRequest::set_service_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcRequest.service_name)
}
inline std::string* ListRpcRequest::mutable_service_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_service_name();
  // @@protoc_insertion_point(field_mutable:com.rpc.ListRpcRequest.service_name)
  return _s;
}
inline const std::string& ListRpcRequest::_internal_service_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.service_name_.Get();
}
inline void ListRpcRequest::_internal_set_service_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.Set(value, GetArena());
}
inline std::string* ListRpcRequest::_internal_mutable_service_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.service_name_.Mutable( GetArena());
}
inline std::string* ListRpcRequest::release_service_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:com.rpc.ListRpcRequest.service_name)
  return _impl_.service_name_.Release();
}
inline void ListRpcRequest::set_allocated_service_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.service_name_.IsDefault()) {
          _impl_.service_name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.rpc.ListRpcRequest.service_name)
}

// bool list_method = 2;
inline void ListRpcRequest::clear_list_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.list_method_ = false;
}
inline bool ListRpcRequest::list_method() const {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcRequest.list_method)
  return _internal_list_method();
}
inline void ListRpcRequest::set_list_method(bool value) {
  _internal_set_list_method(value);
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcRequest.list_method)
}
inline bool ListRpcRequest::_internal_list_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.list_method_;
}
inline void ListRpcRequest::_internal_set_list_method(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.list_method_ = value;
}

// -------------------------------------------------------------------

// ListRpcResponse

// .com.rpc.ErrorCode error = 1;
inline void ListRpcResponse::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = 0;
}
inline ::com::rpc::ErrorCode ListRpcResponse::error() const {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcResponse.error)
  return _internal_error();
}
inline void ListRpcResponse::set_error(::com::rpc::ErrorCode value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcResponse.error)
}
inline ::com::rpc::ErrorCode ListRpcResponse::_internal_error() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::com::rpc::ErrorCode>(_impl_.error_);
}
inline void ListRpcResponse::_internal_set_error(::com::rpc::ErrorCode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = value;
}

// repeated string service_name = 2;
inline int ListRpcResponse::_internal_service_name_size() const {
  return _internal_service_name().size();
}
inline int ListRpcResponse::service_name_size() const {
  return _internal_service_name_size();
}
inline void ListRpcResponse::clear_service_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.Clear();
}
inline std::string* ListRpcResponse::add_service_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_service_name()->Add();
  // @@protoc_insertion_point(field_add_mutable:com.rpc.ListRpcResponse.service_name)
  return _s;
}
inline const std::string& ListRpcResponse::service_name(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcResponse.service_name)
  return _internal_service_name().Get(index);
}
inline std::string* ListRpcResponse::mutable_service_name(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:com.rpc.ListRpcResponse.service_name)
  return _internal_mutable_service_name()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ListRpcResponse::set_service_name(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_service_name()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcResponse.service_name)
}
template <typename Arg_, typename... Args_>
inline void ListRpcResponse::add_service_name(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_service_name(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:com.rpc.ListRpcResponse.service_name)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ListRpcResponse::service_name() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:com.rpc.ListRpcResponse.service_name)
  return _internal_service_name();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ListRpcResponse::mutable_service_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:com.rpc.ListRpcResponse.service_name)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_service_name();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ListRpcResponse::_internal_service_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.service_name_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ListRpcResponse::_internal_mutable_service_name() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.service_name_;
}

// repeated string method_name = 3;
inline int ListRpcResponse::_internal_method_name_size() const {
  return _internal_method_name().size();
}
inline int ListRpcResponse::method_name_size() const {
  return _internal_method_name_size();
}
inline void ListRpcResponse::clear_method_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_name_.Clear();
}
inline std::string* ListRpcResponse::add_method_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_method_name()->Add();
  // @@protoc_insertion_point(field_add_mutable:com.rpc.ListRpcResponse.method_name)
  return _s;
}
inline const std::string& ListRpcResponse::method_name(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.rpc.ListRpcResponse.method_name)
  return _internal_method_name().Get(index);
}
inline std::string* ListRpcResponse::mutable_method_name(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:com.rpc.ListRpcResponse.method_name)
  return _internal_mutable_method_name()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ListRpcResponse::set_method_name(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_method_name()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:com.rpc.ListRpcResponse.method_name)
}
template <typename Arg_, typename... Args_>
inline void ListRpcResponse::add_method_name(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_method_name(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:com.rpc.ListRpcResponse.method_name)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ListRpcResponse::method_name() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:com.rpc.ListRpcResponse.method_name)
  return _internal_method_name();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ListRpcResponse::mutable_method_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:com.rpc.ListRpcResponse.method_name)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_method_name();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ListRpcResponse::_internal_method_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.method_name_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ListRpcResponse::_internal_mutable_method_name() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.method_name_;
}

// -------------------------------------------------------------------

// GetServiceRequest

// string service_name = 1;
inline void GetServiceRequest::clear_service_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.ClearToEmpty();
}
inline const std::string& GetServiceRequest::service_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.rpc.GetServiceRequest.service_name)
  return _internal_service_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GetServiceRequest::set_service_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceRequest.service_name)
}
inline std::string* GetServiceRequest::mutable_service_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_service_name();
  // @@protoc_insertion_point(field_mutable:com.rpc.GetServiceRequest.service_name)
  return _s;
}
inline const std::string& GetServiceRequest::_internal_service_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.service_name_.Get();
}
inline void GetServiceRequest::_internal_set_service_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.Set(value, GetArena());
}
inline std::string* GetServiceRequest::_internal_mutable_service_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.service_name_.Mutable( GetArena());
}
inline std::string* GetServiceRequest::release_service_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:com.rpc.GetServiceRequest.service_name)
  return _impl_.service_name_.Release();
}
inline void GetServiceRequest::set_allocated_service_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.service_name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.service_name_.IsDefault()) {
          _impl_.service_name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.rpc.GetServiceRequest.service_name)
}

// -------------------------------------------------------------------

// GetServiceResponse

// .com.rpc.ErrorCode error = 1;
inline void GetServiceResponse::clear_error() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = 0;
}
inline ::com::rpc::ErrorCode GetServiceResponse::error() const {
  // @@protoc_insertion_point(field_get:com.rpc.GetServiceResponse.error)
  return _internal_error();
}
inline void GetServiceResponse::set_error(::com::rpc::ErrorCode value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceResponse.error)
}
inline ::com::rpc::ErrorCode GetServiceResponse::_internal_error() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::com::rpc::ErrorCode>(_impl_.error_);
}
inline void GetServiceResponse::_internal_set_error(::com::rpc::ErrorCode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_ = value;
}

// repeated string proto_file = 2;
inline int GetServiceResponse::_internal_proto_file_size() const {
  return _internal_proto_file().size();
}
inline int GetServiceResponse::proto_file_size() const {
  return _internal_proto_file_size();
}
inline void GetServiceResponse::clear_proto_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proto_file_.Clear();
}
inline std::string* GetServiceResponse::add_proto_file() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_proto_file()->Add();
  // @@protoc_insertion_point(field_add_mutable:com.rpc.GetServiceResponse.proto_file)
  return _s;
}
inline const std::string& GetServiceResponse::proto_file(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.rpc.GetServiceResponse.proto_file)
  return _internal_proto_file().Get(index);
}
inline std::string* GetServiceResponse::mutable_proto_file(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:com.rpc.GetServiceResponse.proto_file)
  return _internal_mutable_proto_file()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void GetServiceResponse::set_proto_file(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_proto_file()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceResponse.proto_file)
}
template <typename Arg_, typename... Args_>
inline void GetServiceResponse::add_proto_file(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_proto_file(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:com.rpc.GetServiceResponse.proto_file)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
GetServiceResponse::proto_file() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:com.rpc.GetServiceResponse.proto_file)
  return _internal_proto_file();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
GetServiceResponse::mutable_proto_file() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:com.rpc.GetServiceResponse.proto_file)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_proto_file();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
GetServiceResponse::_internal_proto_file() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.proto_file_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
GetServiceResponse::_internal_mutable_proto_file() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.proto_file_;
}

// repeated string proto_file_name = 3;
inline int GetServiceResponse::_internal_proto_file_name_size() const {
  return _internal_proto_file_name().size();
}
inline int GetServiceResponse::proto_file_name_size() const {
  return _internal_proto_file_name_size();
}
inline void GetServiceResponse::clear_proto_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proto_file_name_.Clear();
}
inline std::string* GetServiceResponse::add_proto_file_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_proto_file_name()->Add();
  // @@protoc_insertion_point(field_add_mutable:com.rpc.GetServiceResponse.proto_file_name)
  return _s;
}
inline const std::string& GetServiceResponse::proto_file_name(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.rpc.GetServiceResponse.proto_file_name)
  return _internal_proto_file_name().Get(index);
}
inline std::string* GetServiceResponse::mutable_proto_file_name(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:com.rpc.GetServiceResponse.proto_file_name)
  return _internal_mutable_proto_file_name()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void GetServiceResponse::set_proto_file_name(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_proto_file_name()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:com.rpc.GetServiceResponse.proto_file_name)
}
template <typename Arg_, typename... Args_>
inline void GetServiceResponse::add_proto_file_name(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_proto_file_name(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:com.rpc.GetServiceResponse.proto_file_name)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
GetServiceResponse::proto_file_name() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:com.rpc.GetServiceResponse.proto_file_name)
  return _internal_proto_file_name();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
GetServiceResponse::mutable_proto_file_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:com.rpc.GetServiceResponse.proto_file_name)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_proto_file_name();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
GetServiceResponse::_internal_proto_file_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.proto_file_name_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
GetServiceResponse::_internal_mutable_proto_file_name() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.proto_file_name_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace rpc
}  // namespace com


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_rpc_5fservice_2eproto_2epb_2eh
