//
// Created by fzy on 2024/12/16.
//

#ifndef OSADAPTOR_IO_IPC_UDS__UDS_SYS_INTERFACE_H
#define OSADAPTOR_IO_IPC_UDS__UDS_SYS_INTERFACE_H

/** UDS 独有的一些系统API */

#endif //OSADAPTOR_IO_IPC_UDS__UDS_SYS_INTERFACE_H
