%% An example of Matlab workflow for determining a fixed time delta between two transformations
%% (e.g. one obtained by scan matching the laser, and another from odometry) by comparing the yaw signals

% load in the CSV files generated by tf_stamps_to_csv.py
odom = dlmread('amacal_2017-05-12-20-33-29_0.csv', ' ');
scan_match = dlmread('2017-05-31-17-27-27.csv', ' ');

% create timeseries objects
odom_ts = timeseries(odom(:, 2), odom(:, 1))
scan_match_ts = timeseries(scan_match(:, 2), scan_match(:,1))

% synchronize and resample both signals to a common timebase with uniform Ts = 0.05
[synced_odom, synced_scan_match] = synchronize(odom_ts, scan_match_ts, 'Uniform', 'Interval', 0.05)

% plot yaw angles
% unwrap() is used to eliminate phase jumps (although some remain?)
figure
plot(synced_odom.time(1:end)-synced_odom.time(1), unwrap(synced_odom.data))
hold on
plot(synced_scan_match.time(1:end)-synced_odom.time(1), unwrap(synced_scan_match.data))

% plot yaw difference signal
figure
plot(synced_odom.time(2:end)-synced_odom.time(1), diff(unwrap(synced_odom.data))./diff(synced_odom.time))
hold on
plot(synced_scan_match.time(2:end)-synced_odom.time(1), diff(unwrap(synced_scan_match.data))./diff(synced_scan_match.time))

% the next step would be to use use xcorr() or finddelay()
